--- #YAML:1.0
name:               SAP-Rfc
version:            1.56
abstract:           Perl extension for performing RFC Function calls agains an SAP R/3 System
author:
    - Piers Harding <piers@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
